import antfu from "@antfu/eslint-config";

export default antfu({
  formatters: {
    prettierOptions: {
      printWidth: 100,
      trailingComma: "all",
      singleQuote: false,
      semi: true,
      tabWidth: 2,
      quoteProps: "as-needed",
      jsxSingleQuote: false,
      arrowParens: "always",
    },
  },
  stylistic: false,
  typescript: true,
  name: "rule-engine",
  react: true,
  gitignore: true,
}).append({
  ignores: [
    "README.md",
    "packages/*/README.md",
    "packages/*/CHANGELOG.md",
    "packages/*/dist",
    "packages/*/node_modules",
    "packages/*/coverage",
    "**/*.json",
  ],
  files: ["./packages/**/*.ts", "./packages/**/*.tsx"],
  rules: {
    eqeqeq: "off",
    "prefer-regex-literals": "off",
    "regexp/no-obscure-range": "off",
    "react-refresh/only-export-components": "off",
    "no-labels": "off",
    "no-cond-assign": "off",
    "no-async-promise-executor": "off",
    "no-new": "off",
    "no-console": "off",
    "antfu/top-level-function": "off",
    "ts/no-unsafe-function-type": "off",
    "perfectionist/sort-imports": "off",
    "ts/explicit-function-return-type": "off",
    "regexp/no-unused-capturing-group": "off",
    "node/prefer-global/buffer": "off",
    "node/prefer-global/process": "off",
    "no-throw-literal": "off",
    "ts/ban-ts-comment": "off",
    "ts/method-signature-style": "off",
    "ts/no-non-null-asserted-optional-chain": "off",
    "react-hooks-extra/no-direct-set-state-in-use-effect": "off",
    "react/no-array-index-key": "off",
    "perfectionist/sort-named-imports": ["error", { order: "desc" }],
  },
});
